export interface TarotCard {
  name: string
  number: number
  suit: 'major' | 'wands' | 'cups' | 'swords' | 'pentacles'
  emoji: string
  keywords: string[]
  upright_meaning: string
  reversed_meaning: string
}

export interface DrawnCard extends TarotCard {
  reversed: boolean
  position?: string
}

export const TAROT_DECK: TarotCard[] = [
  // ── Major Arcana ──────────────────────────────────────────
  {
    name: 'The Fool',
    number: 0,
    suit: 'major',
    emoji: '🌟',
    keywords: ['beginnings', 'innocence', 'spontaneity', 'leap of faith'],
    upright_meaning: 'A new chapter is beginning — trust the leap even without a clear landing.',
    reversed_meaning: 'Fear of the unknown is keeping you stuck in a story that has already ended.',
  },
  {
    name: 'The Magician',
    number: 1,
    suit: 'major',
    emoji: '✨',
    keywords: ['willpower', 'manifestation', 'skill', 'resourcefulness'],
    upright_meaning: 'Every tool you need is already in your hands — stop waiting to begin.',
    reversed_meaning: 'Your power is being scattered or misused; realign your intentions before acting.',
  },
  {
    name: 'The High Priestess',
    number: 2,
    suit: 'major',
    emoji: '🌙',
    keywords: ['intuition', 'sacred knowing', 'mystery', 'stillness'],
    upright_meaning: 'The answer you are seeking lives beneath the surface — go inward before going outward.',
    reversed_meaning: 'You are ignoring your intuition in favor of logic that does not fully apply here.',
  },
  {
    name: 'The Empress',
    number: 3,
    suit: 'major',
    emoji: '🌿',
    keywords: ['abundance', 'nurturing', 'creation', 'sensuality'],
    upright_meaning: 'Tend to yourself with the same care you give everything else and watch abundance bloom.',
    reversed_meaning: 'Overgiving and self-neglect are blocking the flow — you cannot pour from empty.',
  },
  {
    name: 'The Emperor',
    number: 4,
    suit: 'major',
    emoji: '🏛️',
    keywords: ['structure', 'authority', 'groundedness', 'discipline'],
    upright_meaning: 'What you build from discipline and order will outlast everything created from chaos.',
    reversed_meaning: 'Rigidity or fear of losing control is creating the very instability you are trying to avoid.',
  },
  {
    name: 'The Hierophant',
    number: 5,
    suit: 'major',
    emoji: '📿',
    keywords: ['tradition', 'mentorship', 'learning', 'spiritual wisdom'],
    upright_meaning: 'A teacher, system, or practice is available to you right now — be open to receiving it.',
    reversed_meaning: 'You are being called to question the belief systems or structures you inherited rather than chose.',
  },
  {
    name: 'The Lovers',
    number: 6,
    suit: 'major',
    emoji: '💕',
    keywords: ['alignment', 'choice', 'values', 'union'],
    upright_meaning: 'This is a moment of deep alignment — choose what is true, not what is comfortable.',
    reversed_meaning: 'A misalignment between your values and your choices is creating inner conflict.',
  },
  {
    name: 'The Chariot',
    number: 7,
    suit: 'major',
    emoji: '⚡',
    keywords: ['willpower', 'momentum', 'direction', 'determination'],
    upright_meaning: 'You have the power to move forward — stop negotiating with yourself and drive.',
    reversed_meaning: 'You are pushing hard but in conflicting directions; gather your focus before moving.',
  },
  {
    name: 'Strength',
    number: 8,
    suit: 'major',
    emoji: '🦁',
    keywords: ['inner strength', 'patience', 'courage', 'compassion'],
    upright_meaning: 'Your power today is in staying soft while staying firm — you do not need to roar to lead.',
    reversed_meaning: 'Self-doubt or force are getting in the way of the quiet, steady strength that is actually yours.',
  },
  {
    name: 'The Hermit',
    number: 9,
    suit: 'major',
    emoji: '🕯️',
    keywords: ['solitude', 'inner guidance', 'wisdom', 'introspection'],
    upright_meaning: 'You need less input from outside right now — the answer is waiting in the quiet.',
    reversed_meaning: 'Isolation has tipped from clarity into avoidance; the world is ready to receive what you know.',
  },
  {
    name: 'Wheel of Fortune',
    number: 10,
    suit: 'major',
    emoji: '🎡',
    keywords: ['change', 'cycles', 'turning point', 'fate'],
    upright_meaning: 'Something is shifting — trust the cycle, it is moving in your favor even if you cannot see it yet.',
    reversed_meaning: 'You are resisting a necessary change; the wheel turns whether or not you release your grip.',
  },
  {
    name: 'Justice',
    number: 11,
    suit: 'major',
    emoji: '⚖️',
    keywords: ['truth', 'fairness', 'accountability', 'clarity'],
    upright_meaning: 'What you have been choosing is returning to you — be honest with yourself about what that is.',
    reversed_meaning: 'Dishonesty with yourself or avoidance of a truth you already know is delaying what you need.',
  },
  {
    name: 'The Hanged Man',
    number: 12,
    suit: 'major',
    emoji: '🌀',
    keywords: ['pause', 'surrender', 'new perspective', 'waiting'],
    upright_meaning: 'Stop trying to force this — a voluntary pause is the only way to see what you have been missing.',
    reversed_meaning: 'You have been suspended long enough; the time for waiting is complete, move forward.',
  },
  {
    name: 'Death',
    number: 13,
    suit: 'major',
    emoji: '🦋',
    keywords: ['transformation', 'endings', 'rebirth', 'release'],
    upright_meaning: 'Something is ending so something better can begin — do not hold onto what is already leaving.',
    reversed_meaning: 'You are clinging to what is already gone, and that attachment is slowing the transformation.',
  },
  {
    name: 'Temperance',
    number: 14,
    suit: 'major',
    emoji: '🌊',
    keywords: ['balance', 'patience', 'flow', 'moderation'],
    upright_meaning: 'Find the middle ground — you are being asked to blend and integrate, not force or rush.',
    reversed_meaning: 'Excess or imbalance is draining what could be sustained and flowing naturally.',
  },
  {
    name: 'The Devil',
    number: 15,
    suit: 'major',
    emoji: '🔗',
    keywords: ['attachment', 'shadow', 'freedom', 'patterns'],
    upright_meaning: 'You have more freedom than you are allowing yourself — examine what you are staying in out of fear.',
    reversed_meaning: 'You are beginning to see the chains clearly and are ready to choose differently.',
  },
  {
    name: 'The Tower',
    number: 16,
    suit: 'major',
    emoji: '🌩️',
    keywords: ['disruption', 'revelation', 'sudden change', 'truth'],
    upright_meaning: 'Something built on a false foundation is breaking down so something real can be built in its place.',
    reversed_meaning: 'You are avoiding a necessary breakdown; the longer the delay, the louder it will eventually arrive.',
  },
  {
    name: 'The Star',
    number: 17,
    suit: 'major',
    emoji: '⭐',
    keywords: ['hope', 'renewal', 'faith', 'healing'],
    upright_meaning: 'You are allowed to hope again — the darkness is passing and you are entering a season of receiving.',
    reversed_meaning: 'Despair or disillusionment is blocking the healing that is genuinely available to you right now.',
  },
  {
    name: 'The Moon',
    number: 18,
    suit: 'major',
    emoji: '🌕',
    keywords: ['illusion', 'intuition', 'subconscious', 'uncertainty'],
    upright_meaning: 'Not everything is what it appears — trust your gut, not the story your mind is telling.',
    reversed_meaning: 'A confusion or fear that has kept you in the dark is beginning to surface and lose its power.',
  },
  {
    name: 'The Sun',
    number: 19,
    suit: 'major',
    emoji: '☀️',
    keywords: ['joy', 'success', 'vitality', 'clarity'],
    upright_meaning: 'You are stepping into a brighter season — let yourself be seen and celebrated.',
    reversed_meaning: 'Joy is available but something is dimming it; release what is standing between you and the light.',
  },
  {
    name: 'Judgement',
    number: 20,
    suit: 'major',
    emoji: '🎺',
    keywords: ['awakening', 'calling', 'reflection', 'reckoning'],
    upright_meaning: 'You are being called toward something higher — answer it without waiting for perfect conditions.',
    reversed_meaning: 'Harsh self-judgment or avoidance of a soul reckoning is keeping you from what is ready for you.',
  },
  {
    name: 'The World',
    number: 21,
    suit: 'major',
    emoji: '🌍',
    keywords: ['completion', 'wholeness', 'integration', 'achievement'],
    upright_meaning: 'A cycle is complete — you have earned this, let yourself feel it before starting the next thing.',
    reversed_meaning: 'You are rushing past completion without integrating the lessons, which will bring you full circle again.',
  },

  // ── Wands ───────────────────────────────────────────────────
  {
    name: 'Ace of Wands',
    number: 1,
    suit: 'wands',
    emoji: '🔥',
    keywords: ['spark', 'inspiration', 'new passion', 'potential'],
    upright_meaning: 'A powerful creative spark is available right now — pick it up and start.',
    reversed_meaning: 'Creative energy is blocked or scattered; wait for clarity before forcing a direction.',
  },
  {
    name: 'Two of Wands',
    number: 2,
    suit: 'wands',
    emoji: '🗺️',
    keywords: ['planning', 'vision', 'future', 'decision'],
    upright_meaning: 'You are standing at the edge of your known world — the bigger path is the one worth choosing.',
    reversed_meaning: 'Fear of leaving the familiar is keeping you planning instead of moving.',
  },
  {
    name: 'Three of Wands',
    number: 3,
    suit: 'wands',
    emoji: '⛵',
    keywords: ['expansion', 'foresight', 'opportunity', 'growth'],
    upright_meaning: 'What you sent out is returning — your efforts are creating expansion, keep watching the horizon.',
    reversed_meaning: 'Delays or obstacles are frustrating your plans; adjust the route without abandoning the destination.',
  },
  {
    name: 'Four of Wands',
    number: 4,
    suit: 'wands',
    emoji: '🎉',
    keywords: ['celebration', 'stability', 'homecoming', 'milestone'],
    upright_meaning: 'A moment of real celebration and stability is here — let yourself rest in it.',
    reversed_meaning: 'A milestone is being overlooked; stop and acknowledge how far you have actually come.',
  },
  {
    name: 'Five of Wands',
    number: 5,
    suit: 'wands',
    emoji: '⚔️',
    keywords: ['conflict', 'competition', 'tension', 'challenge'],
    upright_meaning: 'The friction around you is an invitation to refine your direction and stay in your own lane.',
    reversed_meaning: 'An ongoing conflict is draining your energy; it may be time to disengage and conserve.',
  },
  {
    name: 'Six of Wands',
    number: 6,
    suit: 'wands',
    emoji: '🏆',
    keywords: ['victory', 'recognition', 'confidence', 'success'],
    upright_meaning: 'Recognition and success are here — receive it without minimizing what you built.',
    reversed_meaning: 'You are seeking validation externally; your success is real even when no one is applauding.',
  },
  {
    name: 'Seven of Wands',
    number: 7,
    suit: 'wands',
    emoji: '🛡️',
    keywords: ['defense', 'perseverance', 'standing ground', 'courage'],
    upright_meaning: 'You are worth defending — stand your ground even when it feels like everyone is pushing back.',
    reversed_meaning: 'Exhaustion from constant defense is real; choose your battles and protect your energy.',
  },
  {
    name: 'Eight of Wands',
    number: 8,
    suit: 'wands',
    emoji: '💫',
    keywords: ['speed', 'momentum', 'movement', 'swift action'],
    upright_meaning: 'Things are moving fast — align with the momentum rather than trying to slow it down.',
    reversed_meaning: 'Delays and scattered energy are slowing what could be moving quickly; focus on one thing.',
  },
  {
    name: 'Nine of Wands',
    number: 9,
    suit: 'wands',
    emoji: '🧱',
    keywords: ['resilience', 'persistence', 'last push', 'guarded'],
    upright_meaning: 'You are almost there — rest if you must, but do not quit when you are this close.',
    reversed_meaning: 'Burnout and over-guarding are real; it is okay to put down what you have been carrying alone.',
  },
  {
    name: 'Ten of Wands',
    number: 10,
    suit: 'wands',
    emoji: '🎒',
    keywords: ['burden', 'overcommitment', 'pressure', 'completion'],
    upright_meaning: 'You are carrying more than your share — identify what you can put down or delegate.',
    reversed_meaning: 'The burden is breaking you; releasing even one thing will shift everything.',
  },
  {
    name: 'Page of Wands',
    number: 11,
    suit: 'wands',
    emoji: '🌱',
    keywords: ['curiosity', 'enthusiasm', 'exploration', 'creative messages'],
    upright_meaning: 'A new creative direction is calling — follow the excitement without needing the full plan.',
    reversed_meaning: 'Creative energy is burning fast without direction; channel enthusiasm into one focused effort.',
  },
  {
    name: 'Knight of Wands',
    number: 12,
    suit: 'wands',
    emoji: '🐎',
    keywords: ['passion', 'adventure', 'impulse', 'fearless action'],
    upright_meaning: 'Bold, fast action is exactly right here — move with confidence before overthinking returns.',
    reversed_meaning: 'Impulsive energy is creating chaos; pause long enough to check your direction.',
  },
  {
    name: 'Queen of Wands',
    number: 13,
    suit: 'wands',
    emoji: '🌻',
    keywords: ['confidence', 'charisma', 'passion', 'warmth'],
    upright_meaning: 'You are in your power — lead from that warm, fierce confidence and let yourself be seen.',
    reversed_meaning: 'Insecurity or burnout has dimmed your fire; tend to yourself before performing for anyone else.',
  },
  {
    name: 'King of Wands',
    number: 14,
    suit: 'wands',
    emoji: '👑',
    keywords: ['leadership', 'vision', 'boldness', 'mastery'],
    upright_meaning: 'Lead with bold vision and decisive energy — your authority on this is not up for debate.',
    reversed_meaning: 'Ego or impulsiveness is undermining your leadership; wisdom is stronger than force right now.',
  },

  // ── Cups ────────────────────────────────────────────────────
  {
    name: 'Ace of Cups',
    number: 1,
    suit: 'cups',
    emoji: '💧',
    keywords: ['new love', 'emotional opening', 'intuition', 'overflow'],
    upright_meaning: 'A new emotional beginning is pouring in — open your heart and receive it.',
    reversed_meaning: 'Emotional walls or past hurt are blocking a connection that is genuinely reaching for you.',
  },
  {
    name: 'Two of Cups',
    number: 2,
    suit: 'cups',
    emoji: '💞',
    keywords: ['partnership', 'connection', 'mutual love', 'harmony'],
    upright_meaning: 'A deep, equal connection is present or forming — honor it with honesty and care.',
    reversed_meaning: 'Imbalance, disconnection, or unspoken tension is creating distance in a meaningful bond.',
  },
  {
    name: 'Three of Cups',
    number: 3,
    suit: 'cups',
    emoji: '🥂',
    keywords: ['celebration', 'friendship', 'community', 'joy'],
    upright_meaning: 'Your people are here — celebrate together and let yourself be held by your community.',
    reversed_meaning: 'Overindulgence or isolation is pulling you away from the connections that sustain you.',
  },
  {
    name: 'Four of Cups',
    number: 4,
    suit: 'cups',
    emoji: '😔',
    keywords: ['apathy', 'contemplation', 'withdrawal', 'discontent'],
    upright_meaning: 'A period of introspection is necessary — what feels like stagnation is actually recalibration.',
    reversed_meaning: 'You are beginning to see what has been available all along; open your eyes to what is being offered.',
  },
  {
    name: 'Five of Cups',
    number: 5,
    suit: 'cups',
    emoji: '😢',
    keywords: ['grief', 'loss', 'regret', 'mourning'],
    upright_meaning: 'Grief is valid and needs space — but there is still something standing behind you worth turning toward.',
    reversed_meaning: 'The mourning period is lifting; it is safe to move forward and allow healing.',
  },
  {
    name: 'Six of Cups',
    number: 6,
    suit: 'cups',
    emoji: '🌸',
    keywords: ['nostalgia', 'innocence', 'healing memories', 'childhood'],
    upright_meaning: 'The past holds a gift worth revisiting — an old joy, relationship, or memory carries a message.',
    reversed_meaning: 'Living in the past is preventing you from building the present that is actually waiting for you.',
  },
  {
    name: 'Seven of Cups',
    number: 7,
    suit: 'cups',
    emoji: '🌫️',
    keywords: ['fantasy', 'choices', 'illusion', 'wishful thinking'],
    upright_meaning: 'Many options are visible but not all are real — get clear on what you actually want versus what looks good.',
    reversed_meaning: 'The fog is clearing and a true choice is emerging; trust the clarity that is arriving.',
  },
  {
    name: 'Eight of Cups',
    number: 8,
    suit: 'cups',
    emoji: '🚶',
    keywords: ['walking away', 'abandonment', 'search for meaning', 'transition'],
    upright_meaning: 'Leaving what no longer fills you — even when it looks fine on the outside — is the courageous choice.',
    reversed_meaning: 'You are torn between staying and leaving; clarity about what you truly need will make this clear.',
  },
  {
    name: 'Nine of Cups',
    number: 9,
    suit: 'cups',
    emoji: '😊',
    keywords: ['contentment', 'satisfaction', 'wish fulfilled', 'pleasure'],
    upright_meaning: 'A wish is fulfilled or very near — let yourself feel the satisfaction of what you have created.',
    reversed_meaning: 'Satisfaction is close but something small is being overlooked that would complete this picture.',
  },
  {
    name: 'Ten of Cups',
    number: 10,
    suit: 'cups',
    emoji: '🌈',
    keywords: ['harmony', 'fulfillment', 'family', 'emotional bliss'],
    upright_meaning: 'Emotional wholeness and deep belonging are either here or on their way — trust the love that is real.',
    reversed_meaning: 'An idealized version of happiness is distracting you from the real love already present.',
  },
  {
    name: 'Page of Cups',
    number: 11,
    suit: 'cups',
    emoji: '🐟',
    keywords: ['intuitive messages', 'creativity', 'sensitivity', 'dreams'],
    upright_meaning: 'A tender, intuitive message is arriving — pay attention to dreams, feelings, and unexpected signs.',
    reversed_meaning: 'Emotional immaturity or fantasy is coloring your perception; ground your feelings in what is real.',
  },
  {
    name: 'Knight of Cups',
    number: 12,
    suit: 'cups',
    emoji: '🦢',
    keywords: ['romance', 'charm', 'following the heart', 'idealism'],
    upright_meaning: 'Follow the heart-pull without overthinking it — this is one of those moments for feeling, not analyzing.',
    reversed_meaning: 'Romantic idealism or emotional unavailability is creating a connection that looks deeper than it is.',
  },
  {
    name: 'Queen of Cups',
    number: 13,
    suit: 'cups',
    emoji: '🌊',
    keywords: ['emotional intelligence', 'intuition', 'compassion', 'nurturing'],
    upright_meaning: 'Lead from your emotional wisdom right now — your capacity to feel deeply is the gift, not the liability.',
    reversed_meaning: 'You are absorbing others\' emotions without boundaries; return to yourself before giving more.',
  },
  {
    name: 'King of Cups',
    number: 14,
    suit: 'cups',
    emoji: '🌊',
    keywords: ['emotional mastery', 'calm wisdom', 'balance', 'compassionate authority'],
    upright_meaning: 'Master your emotions without suppressing them — respond from wisdom, not reaction.',
    reversed_meaning: 'Emotional manipulation or repression is creating distance; truth and vulnerability are the way through.',
  },

  // ── Swords ──────────────────────────────────────────────────
  {
    name: 'Ace of Swords',
    number: 1,
    suit: 'swords',
    emoji: '⚔️',
    keywords: ['clarity', 'truth', 'breakthrough', 'new perspective'],
    upright_meaning: 'A clear, sharp truth is cutting through confusion — receive it even if it is uncomfortable.',
    reversed_meaning: 'Mental fog or confusion is blocking clarity; the truth is there but something is distorting it.',
  },
  {
    name: 'Two of Swords',
    number: 2,
    suit: 'swords',
    emoji: '🙈',
    keywords: ['indecision', 'stalemate', 'avoidance', 'balance'],
    upright_meaning: 'A decision is being avoided — the discomfort of not choosing is greater than the discomfort of choosing.',
    reversed_meaning: 'A decision you have been avoiding is now demanding to be made; the information you need is actually here.',
  },
  {
    name: 'Three of Swords',
    number: 3,
    suit: 'swords',
    emoji: '💔',
    keywords: ['heartbreak', 'grief', 'betrayal', 'sorrow'],
    upright_meaning: 'A real hurt or loss needs to be fully felt — numbness and bypassing will only delay the healing.',
    reversed_meaning: 'Healing is underway and the sharpest pain is beginning to lift; let yourself emerge from this.',
  },
  {
    name: 'Four of Swords',
    number: 4,
    suit: 'swords',
    emoji: '😴',
    keywords: ['rest', 'recovery', 'retreat', 'contemplation'],
    upright_meaning: 'Rest is not laziness right now — your mind needs space to process before you can move forward well.',
    reversed_meaning: 'Restlessness or avoidance of stillness is keeping the recovery from completing; stop moving.',
  },
  {
    name: 'Five of Swords',
    number: 5,
    suit: 'swords',
    emoji: '🏳️',
    keywords: ['conflict', 'defeat', 'tension', 'pyrrhic victory'],
    upright_meaning: 'Not every battle is worth winning — consider what the victory actually costs.',
    reversed_meaning: 'A conflict that has been draining you is coming to an end; move toward resolution, not revenge.',
  },
  {
    name: 'Six of Swords',
    number: 6,
    suit: 'swords',
    emoji: '🚤',
    keywords: ['transition', 'moving on', 'calmer waters', 'healing journey'],
    upright_meaning: 'You are moving from turbulence toward calmer waters — trust the direction you are heading.',
    reversed_meaning: 'A transition is being resisted or delayed; you cannot stay in the rough water forever.',
  },
  {
    name: 'Seven of Swords',
    number: 7,
    suit: 'swords',
    emoji: '🦊',
    keywords: ['strategy', 'deception', 'stealth', 'solo path'],
    upright_meaning: 'Strategic thinking and selective disclosure are sometimes necessary — be wise about who sees your whole plan.',
    reversed_meaning: 'A deception — by you or toward you — is coming to light; honesty is the only clean path forward.',
  },
  {
    name: 'Eight of Swords',
    number: 8,
    suit: 'swords',
    emoji: '🕸️',
    keywords: ['restriction', 'trapped', 'self-limiting beliefs', 'victim mentality'],
    upright_meaning: 'The trap you feel is largely constructed by your own mind — question the story before accepting it as fixed.',
    reversed_meaning: 'You are beginning to see through the mental prison; the way out is becoming visible.',
  },
  {
    name: 'Nine of Swords',
    number: 9,
    suit: 'swords',
    emoji: '😰',
    keywords: ['anxiety', 'worry', 'nightmares', 'mental anguish'],
    upright_meaning: 'Anxiety is real but it is not the full picture — what you fear at 3 AM rarely looks the same at noon.',
    reversed_meaning: 'The worst of the mental spiral is releasing; reach for one calming thought and follow it.',
  },
  {
    name: 'Ten of Swords',
    number: 10,
    suit: 'swords',
    emoji: '🌅',
    keywords: ['rock bottom', 'ending', 'defeat', 'new dawn'],
    upright_meaning: 'This is the end of a painful chapter — and right behind it is the beginning of something entirely new.',
    reversed_meaning: 'You are holding yourself in a painful ending longer than necessary; the door to new is already open.',
  },
  {
    name: 'Page of Swords',
    number: 11,
    suit: 'swords',
    emoji: '🌬️',
    keywords: ['curiosity', 'mental agility', 'new ideas', 'truth-seeking'],
    upright_meaning: 'Curious, sharp-minded energy is alive here — ask the questions no one else is asking.',
    reversed_meaning: 'Sharp words without wisdom or all talk without action is draining the potential of a good mind.',
  },
  {
    name: 'Knight of Swords',
    number: 12,
    suit: 'swords',
    emoji: '💨',
    keywords: ['speed', 'ambition', 'direct action', 'truth'],
    upright_meaning: 'Move fast and speak directly — this is not the moment for softening or hesitation.',
    reversed_meaning: 'Rushing in without thinking or speaking before listening is creating unnecessary damage.',
  },
  {
    name: 'Queen of Swords',
    number: 13,
    suit: 'swords',
    emoji: '🗡️',
    keywords: ['sharp mind', 'independence', 'clarity', 'discernment'],
    upright_meaning: 'Cut through confusion with clear thinking and honest words — you see what others do not.',
    reversed_meaning: 'Coldness, bitterness, or overly critical thinking is isolating you from the softness you also need.',
  },
  {
    name: 'King of Swords',
    number: 14,
    suit: 'swords',
    emoji: '⚖️',
    keywords: ['intellectual power', 'authority', 'truth', 'strategy'],
    upright_meaning: 'Lead with clear thinking, ethical judgment, and decisive communication — your clarity is your power.',
    reversed_meaning: 'Mental manipulation or abuse of authority is creating harm; return to truth and fairness.',
  },

  // ── Pentacles ───────────────────────────────────────────────
  {
    name: 'Ace of Pentacles',
    number: 1,
    suit: 'pentacles',
    emoji: '🌱',
    keywords: ['new opportunity', 'material beginnings', 'abundance', 'groundedness'],
    upright_meaning: 'A real, tangible opportunity is in your hands — plant it with care and it will grow.',
    reversed_meaning: 'A material opportunity is being missed or lost through poor planning or lack of grounding.',
  },
  {
    name: 'Two of Pentacles',
    number: 2,
    suit: 'pentacles',
    emoji: '🤹',
    keywords: ['balance', 'adaptability', 'juggling', 'flexibility'],
    upright_meaning: 'You are managing more than most people could — prioritize ruthlessly and let the rest wait.',
    reversed_meaning: 'The juggling act is about to drop something; simplify before the overwhelm forces the choice.',
  },
  {
    name: 'Three of Pentacles',
    number: 3,
    suit: 'pentacles',
    emoji: '🏗️',
    keywords: ['teamwork', 'skill', 'collaboration', 'mastery'],
    upright_meaning: 'What you are building together is stronger than what any one of you could build alone.',
    reversed_meaning: 'Ego, poor collaboration, or working in isolation is slowing progress on something that needs a team.',
  },
  {
    name: 'Four of Pentacles',
    number: 4,
    suit: 'pentacles',
    emoji: '💰',
    keywords: ['security', 'control', 'holding on', 'materialism'],
    upright_meaning: 'Building security and protecting what you have is wise — just watch where protection becomes hoarding.',
    reversed_meaning: 'Greed, possessiveness, or financial fear is contracting you; generosity and openness will expand things again.',
  },
  {
    name: 'Five of Pentacles',
    number: 5,
    suit: 'pentacles',
    emoji: '❄️',
    keywords: ['hardship', 'lack', 'isolation', 'adversity'],
    upright_meaning: 'A season of lack or financial stress is real — and support is closer than it appears right now.',
    reversed_meaning: 'The hardship is beginning to lift; open your eyes to the help and resources that have been there.',
  },
  {
    name: 'Six of Pentacles',
    number: 6,
    suit: 'pentacles',
    emoji: '🤲',
    keywords: ['generosity', 'giving and receiving', 'charity', 'balance'],
    upright_meaning: 'Give where you can and receive without guilt — abundance flows when the exchange is balanced.',
    reversed_meaning: 'A lopsided exchange of energy or money is depleting you; reassert fair exchange.',
  },
  {
    name: 'Seven of Pentacles',
    number: 7,
    suit: 'pentacles',
    emoji: '🌾',
    keywords: ['patience', 'investment', 'long-term vision', 'assessment'],
    upright_meaning: 'Take a moment to assess what you have been growing — the harvest will come but timing is everything.',
    reversed_meaning: 'Impatience or poor investment of energy and money is working against the long-term vision.',
  },
  {
    name: 'Eight of Pentacles',
    number: 8,
    suit: 'pentacles',
    emoji: '🔨',
    keywords: ['diligence', 'skill-building', 'mastery', 'dedication'],
    upright_meaning: 'Master the craft in front of you — quiet, dedicated work right now creates the platform for everything else.',
    reversed_meaning: 'Perfectionism or scattered focus is preventing the depth of work that would actually change things.',
  },
  {
    name: 'Nine of Pentacles',
    number: 9,
    suit: 'pentacles',
    emoji: '🌺',
    keywords: ['abundance', 'self-sufficiency', 'luxury', 'independence'],
    upright_meaning: 'You have built something real and beautiful — let yourself enjoy the independence you created.',
    reversed_meaning: 'Overwork or self-denial is preventing you from enjoying what you have already built.',
  },
  {
    name: 'Ten of Pentacles',
    number: 10,
    suit: 'pentacles',
    emoji: '🏡',
    keywords: ['legacy', 'wealth', 'family', 'long-term stability'],
    upright_meaning: 'You are building something that will outlast this season — tend to the legacy, not just the moment.',
    reversed_meaning: 'A conflict over values, money, or family is threatening the stability you have worked to build.',
  },
  {
    name: 'Page of Pentacles',
    number: 11,
    suit: 'pentacles',
    emoji: '📚',
    keywords: ['study', 'opportunity', 'practical planning', 'curiosity'],
    upright_meaning: 'A new skill, study, or practical opportunity is worth investing your attention in right now.',
    reversed_meaning: 'Daydreaming without action or poor follow-through is keeping opportunity from becoming reality.',
  },
  {
    name: 'Knight of Pentacles',
    number: 12,
    suit: 'pentacles',
    emoji: '🐂',
    keywords: ['methodical', 'reliable', 'hard work', 'patience'],
    upright_meaning: 'Slow, steady, methodical effort is exactly right here — trust the pace and keep showing up.',
    reversed_meaning: 'Stubbornness or boredom with the slow pace is creating resistance to the very process that will work.',
  },
  {
    name: 'Queen of Pentacles',
    number: 13,
    suit: 'pentacles',
    emoji: '🌿',
    keywords: ['nurturing', 'practical abundance', 'warmth', 'resourcefulness'],
    upright_meaning: 'Tend to home, body, finances, and relationships with equal care — you create abundance through presence.',
    reversed_meaning: 'Neglect of your own physical and material needs is creating instability everywhere else.',
  },
  {
    name: 'King of Pentacles',
    number: 14,
    suit: 'pentacles',
    emoji: '💎',
    keywords: ['wealth', 'business mastery', 'security', 'stability'],
    upright_meaning: 'Lead with practical wisdom, long-term thinking, and generosity — you know how to build real wealth.',
    reversed_meaning: 'Stubbornness, greed, or over-materialism is blocking the abundance that could flow through you.',
  },
]

export function drawCards(n: number): DrawnCard[] {
  const deck = [...TAROT_DECK]
  for (let i = deck.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[deck[i], deck[j]] = [deck[j], deck[i]]
  }
  return deck.slice(0, n).map(card => ({
    ...card,
    reversed: Math.random() < 0.3,
  }))
}
